'use strict';

const globals = require('globals');

/**
 * Flat config port of the legacy .eslintrc.
 *
 * Rules removed in ESLint 9 are mapped to their replacements where one exists:
 *   no-negated-in-lhs      -> no-unsafe-negation
 *   no-empty-label         -> no-labels
 *   space-after-keywords   -> keyword-spacing
 *   space-return-throw-case-> keyword-spacing
 *   no-spaced-func         -> func-call-spacing
 *   no-native-reassign     -> no-global-assign
 *
 * The Node.js/CommonJS rules the old config enabled (handle-callback-err,
 * no-mixed-requires, no-new-require, no-path-concat, no-sync) were removed
 * from ESLint core in v9 and now live in eslint-plugin-n. They are dropped
 * here rather than pulling in another plugin.
 */
module.exports = [
  {
    files: ['**/*.js', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: {
      'comma-dangle': 'off',
      'no-cond-assign': 'error',
      'no-console': 'off',
      'no-constant-condition': 'error',
      'no-control-regex': 'off',
      'no-debugger': 'off',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-inner-declarations': ['error', 'functions'],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-unsafe-negation': 'error',
      'no-obj-calls': 'error',
      'no-regex-spaces': 'error',
      'no-sparse-arrays': 'error',
      'no-unreachable': 'error',
      'use-isnan': 'error',
      'valid-jsdoc': 'off',
      'valid-typeof': 'error',
      'block-scoped-var': 'off',
      complexity: 'off',
      'consistent-return': 'off',
      'default-case': 'off',
      'dot-notation': 'off',
      eqeqeq: 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-div-regex': 'error',
      'no-labels': 'error',
      'no-eq-null': 'off',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-lone-blocks': 'off',
      'no-loop-func': 'off',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-global-assign': 'error',
      'no-new': 'error',
      'no-new-func': 'off',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'off',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'off',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': 'off',
      'no-void': 'error',
      'no-warning-comments': 'off',
      'no-with': 'error',
      radix: 'error',
      'vars-on-top': 'off',
      'wrap-iife': 'error',
      yoda: ['error', 'never', { exceptRange: true }],
      strict: 'off',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-unused-vars': ['error', { vars: 'all', args: 'after-used' }],
      'no-use-before-define': 'off',
      curly: 'off',
      indent: ['error', 2, { SwitchCase: 2 }],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      camelcase: ['error', { properties: 'always' }],
      'comma-spacing': 'off',
      'comma-style': 'off',
      'consistent-this': 'off',
      'eol-last': 'error',
      'func-names': 'off',
      'func-style': 'off',
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'keyword-spacing': 'error',
      'func-call-spacing': 'error',
      'max-nested-callbacks': 'off',
      'new-cap': 'off',
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-inline-comments': 'off',
      'no-lonely-if': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multiple-empty-lines': 'off',
      'no-nested-ternary': 'off',
      'no-new-object': 'error',
      'no-ternary': 'off',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'off',
      'one-var': 'off',
      'operator-assignment': ['error', 'always'],
      'padded-blocks': 'off',
      'quote-props': ['error', 'as-needed'],
      semi: ['error', 'always'],
      'semi-spacing': ['error', { before: false, after: true }],
      'sort-vars': 'off',
      'space-before-blocks': ['error', 'always'],
      'space-in-parens': 'off',
      'space-infix-ops': ['error', { int32Hint: false }],
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'spaced-comment': ['error', 'always'],
      'wrap-regex': 'off',
      'no-var': 'off',
      'max-len': ['error', 130, 4],
    },
  },
  {
    files: ['test/**/*.js', 'test/**/*.cjs'],
    languageOptions: {
      globals: {
        ...globals.mocha,
        expect: 'readonly',
        assert: 'readonly',
      },
    },
  },
  {
    files: ['scripts/**/*.cjs', 'test/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
    },
  },
  {
    files: ['test/benchmark/seed.js'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          globalReturn: true,
        },
      },
      sourceType: 'commonjs',
    },
  },
];
