import { delay, sequelize, Promise, beforeRemoveAllTables, markFilterable } from '../support/helper.js';

/* eslint-disable prefer-const -- Preserve legacy multi-declarator fixtures during the runner-only migration. */

import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi
} from 'vitest';
import Sequelize, { Op } from 'sequelize';

import resolver from '../../src/resolver.js';
import { createConnection } from '../../src/relay.js';
import JSONType from '../../src/types/jsonType.js';

import {
  graphql,
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLString,
  GraphQLInt,
  GraphQLNonNull,
  GraphQLList
} from 'graphql';

type ResolverModel = ReturnType<typeof sequelize.define>;
type ResolverInstance = Awaited<ReturnType<ResolverModel['create']>>;

interface ResolverState {
  projectA: ResolverInstance;
  projectB: ResolverInstance;
  userA: ResolverInstance;
  userB: ResolverInstance;
  users: ResolverInstance[];
  updateUser: ResolverInstance;
}

const state = {} as ResolverState;

describe('resolver', function () {
  beforeRemoveAllTables();

  let User;
  let Task;
  let Project;
  let Label: ResolverModel;
  let taskType: GraphQLObjectType;
  let userType: GraphQLObjectType;
  let projectType: GraphQLObjectType;
  let labelType: GraphQLObjectType;
  let schema: GraphQLSchema;

  /**
   * Setup the a) testing db schema and b) the according GraphQL types
   *
   * The schema consists of a User that has Tasks.
   * A Task belongs to a Project, which can have Labels.
   */
  beforeAll(() => {
    sequelize.modelManager.models = [];
    sequelize.models = {};

    User = sequelize.define('user', {
      name: Sequelize.STRING,
      myVirtual: {
        type: Sequelize.VIRTUAL,
        get: function () {
          return 'lol';
        }
      }
    });

    Task = sequelize.define('task', {
      title: Sequelize.STRING,
      createdAt: {
        type: Sequelize.DATE,
        field: 'created_at',
        defaultValue: Sequelize.NOW
      },
      taskVirtual: {
        type: Sequelize.VIRTUAL,
        get: function () {
          return 'tasktask';
        }
      }
    }, {
      timestamps: false
    });

    Project = sequelize.define('project', {
      name: Sequelize.STRING
    }, {
      timestamps: false
    });

    Label = sequelize.define('label', {
      name: Sequelize.STRING
    }, {
      timestamps: false
    });

    User.Tasks = User.hasMany(Task, {as: 'tasks', foreignKey: 'userId'});
    Task.User = Task.belongsTo(User, {as: 'user', foreignKey: 'userId'});

    Task.Project = Task.belongsTo(Project, {as: 'project', foreignKey: 'projectId'});
    Project.Labels = Project.hasMany(Label, {as: 'labels'});

    // These specs query by primary key (user(id: N), task(id: N)). `id` is
    // generated by sequelize rather than declared by the fixture, so it has to
    // be opted in explicitly or argsToFindOptions drops the argument and the
    // query returns an arbitrary row.
    markFilterable(User, 'id');
    markFilterable(Task, 'id');
    markFilterable(Project, 'id');
    markFilterable(Label, 'id');

    labelType = new GraphQLObjectType({
      name: 'Label',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        },
        name: {
          type: GraphQLString
        }
      }
    });

    projectType = new GraphQLObjectType({
      name: 'Project',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        },
        name: {
          type: GraphQLString
        },
        labels: {
          type: new GraphQLList(labelType),
          resolve: resolver(Project.Labels)
        }
      }
    });

    taskType = new GraphQLObjectType({
      name: 'Task',
      description: 'A task',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        },
        title: {
          type: GraphQLString
        },
        taskVirtual: {
          type: GraphQLString
        },
        project: {
          type: projectType,
          resolve: resolver(Task.Project)
        }
      }
    });

    userType = new GraphQLObjectType({
      name: 'User',
      description: 'A user',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt),
        },
        name: {
          type: GraphQLString,
        },
        myVirtual: {
          type: GraphQLString
        },
        tasks: {
          type: new GraphQLList(taskType),
          args: {
            limit: {
              type: GraphQLInt
            },
            offset: {
              type: GraphQLInt
            },
            order: {
              type: GraphQLString
            },
            first: {
              type: GraphQLInt
            }
          },
          resolve: resolver(() => User.Tasks, {
            before: function (options, args) {
              if (args.first) {
                options.order = options.order || [];
                options.order.push(['created_at', 'ASC']);

                if (args.first !== 0) {
                  options.limit = args.first;
                }
              }

              return options;
            }
          })
        },
        tasksByIds: {
          type: new GraphQLList(taskType),
          args: {
            ids: {
              type: new GraphQLList(GraphQLInt)
            }
          },
          resolve: resolver(User.Tasks, {
            before: (options, args) => {
              options.where = options.where || {};
              // Sequelize 6 removed the string operator form ($in); operators
              // are Symbols now. The old syntax is treated as a literal column
              // key and stringifies to '[object Object]' in the query.
              options.where.id = { [Op.in]: args.ids };
              return options;
            }
          })
        }
      }
    });

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          user: {
            type: userType,
            args: {
              id: {
                type: new GraphQLNonNull(GraphQLInt)
              }
            },
            resolve: resolver(User, {
              contextToOptions: {
                a: 'a',
                b: 'c'
              }
            })
          },
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              },
              where: {
                type: JSONType
              }
            },
            resolve: resolver(User)
          }
        }
      })
    });
  });

  /**
   * Now fill the testing DB with fixture values
   * We'll have projectA & projectB with two random labels each,
   * and two users each with some tasks that belong to those projects.
   */
  beforeAll(() => {
    let taskId = 0
      , projectId = 0;

    return Promise.resolve(sequelize.sync({force: true})).then(function () {
      return Promise.join(
        Project.create({
          id: ++projectId,
          name: 'b' + Math.random().toString(),
          labels: [
            {name: Math.random().toString()},
            {name: Math.random().toString()}
          ]
        }, {
          include: [
            Project.Labels
          ]
        }),
        Project.create({
          id: ++projectId,
          name: 'a' + Math.random().toString(),
          labels: [
            {name: Math.random().toString()},
            {name: Math.random().toString()}
          ]
        }, {
          include: [
            Project.Labels
          ]
        })
      ).then(([projectA, projectB]) => {
        state.projectA = projectA;
        state.projectB = projectB;
      }).then(() => {
        return Promise.all([
          User.create({
            id: 1,
            name: 'b' + Math.random().toString(),
            tasks: [
              {
                id: ++taskId,
                title: Math.random().toString(),
                createdAt: new Date(Date.UTC(2014, 5, 11)),
                projectId: state.projectA.id
              },
              {
                id: ++taskId,
                title: Math.random().toString(),
                createdAt: new Date(Date.UTC(2014, 5, 16)),
                projectId: state.projectB.id
              },
              {
                id: ++taskId,
                title: Math.random().toString(),
                createdAt: new Date(Date.UTC(2014, 5, 20)),
                projectId: state.projectA.id
              }
            ]
          }, {
            include: [User.Tasks]
          }),
          User.create({
            id: 2,
            name: 'a' + Math.random().toString(),
            tasks: [
              {
                id: ++taskId,
                title: Math.random().toString(),
                projectId: state.projectB.id
              },
              {
                id: ++taskId,
                title: Math.random().toString(),
                projectId: state.projectB.id
              }
            ]
          }, {
            include: [User.Tasks]
          }),
        ]).then(([userA, userB]) => {
          state.userA = userA;
          state.userB = userB;

          state.users = [userA, userB];
        });
      });
    });
  });

  beforeEach(() => {
    vi.spyOn(User, 'findOne');
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should resolve a plain result with a single model', () => {
    const user = state.userB;

    return graphql({
      schema: schema,
      source: `
        {
          user(id: ${user.id}) {
            name
            myVirtual
          }
        }
      `,
      contextValue: {},
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data).to.deep.equal({
        user: {
          name: user.name,
          myVirtual: 'lol'
        }
      });
    });
  });

  it('should map context to find options', () => {
    const user = state.userB;

    return graphql({
      schema,
      source: `
        {
          user(id: ${user.id}) {
            name
            myVirtual
          }
        }
      `,
      contextValue: {a: 1, b: 2}
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data).to.deep.equal({
        user: {
          name: user.name,
          myVirtual: 'lol'
        }
      });

      expect(vi.mocked(User.findOne).mock.calls[0][0].a).to.equal(1);
      expect(vi.mocked(User.findOne).mock.calls[0][0].c).to.equal(2);
    });
  });

  it('should resolve a plain result with an aliased field', () => {
    const user = state.userB;

    return graphql({
      schema,
      source: `
        {
          user(id: ${user.id}) {
            name
            magic: myVirtual
          }
        }
      `,
      contextValue: {},
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data).to.deep.equal({
        user: {
          name: user.name,
          magic: 'lol'
        }
      });
    });
  });

  it('should resolve a plain result with a single model and aliases', () => {
    const userA = state.userA
      , userB = state.userB;

    return graphql({
      schema,
      source: `
        {
          userA: user(id: ${userA.id}) {
            name
            myVirtual
          }
          userB: user(id: ${userB.id}) {
            name
            myVirtual
          }
        }
      `,
      contextValue: {},
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data).to.deep.equal({
        userA: {
          name: userA.name,
          myVirtual: 'lol'
        },
        userB: {
          name: userB.name,
          myVirtual: 'lol'
        }
      });
    });
  });

  it('should resolve a array result with a model and aliased includes', () => {
    return graphql({
      schema,
      source: `
        {
          users {
            name

            first: tasks(limit: 1) {
              title
            }

            rest: tasks(offset: 1, limit: 99) {
              title
            }
          }
        }
      `,
      contextValue: {},
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      result.data.users.forEach(function (user) {
        expect(user.first).to.be.ok;
        expect(user.rest).to.be.ok;
      });
    });
  });

  it('should resolve a array result with a model and aliased includes and __typename', () => {
    return graphql({
      schema,
      source: `
        {
          users {
            name

            first: tasks(limit: 1) {
              title
              __typename
            }
          }
        }
      `
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      result.data.users.forEach(function (user) {
        expect(user.first[0].__typename).to.equal('Task');
      });
    });
  });

  it('should resolve an array result with a single model', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            name
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length.above(0);

      const usersNames = users.map(user => ({name: user.name}));
      // As the GraphQL query doesn't specify an ordering,
      // the order of the two lists can not be asserted.
      expect(result.data.users).to.deep.have.members(usersNames);
    });
  });

  it('should allow amending the find for a array result with a single model', () => {
    let user = state.userA
      , schema;

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              }
            },
            resolve: resolver(User, {
              before: function (options, args, {name}) {
                options.where = options.where || {};
                options.where.name = name;
                return options;
              }
            })
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name
          }
        }
      `,
      contextValue: {
        name: user.name
      },
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(1);
      expect(result.data.users[0].name).to.equal(user.name);
    });
  });

  it('should allow parsing the find for a array result with a single model', () => {
    let users = state.users
      , schema;

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              }
            },
            resolve: resolver(User, {
              after: function (result) {
                return result.map(function () {
                  return {
                    name: '11!!'
                  };
                });
              }
            })
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(users.length);
      result.data.users.forEach(function (user) {
        expect(user.name).to.equal('11!!');
      });
    });
  });

  it('should work with a resolver through a proxy', () => {
    let users = state.users
      , schema
      , userType
      , taskType;

    taskType = new GraphQLObjectType({
      name: 'Task',
      description: 'A task',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        },
        title: {
          type: GraphQLString
        }
      }
    });

    userType = new GraphQLObjectType({
      name: 'User',
      description: 'A user',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt),
        },
        name: {
          type: GraphQLString,
        },
        tasks: {
          type: new GraphQLList(taskType),
          resolve: (function () {
            const $resolver = resolver(User.Tasks);
            const $proxy = function (...args) {
              return $resolver(...args);
            };

            $proxy.$proxy = $resolver;
            return $proxy;
          }())
        }
      }
    });

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              }
            },
            resolve: resolver(User)
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name,
            tasks {
              title
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).to.have.length.above(0);
      });
    });
  });

  it('should work with a passthrough resolver and a duplicated query', () => {
    let users = state.users
      , schema
      , userType
      , taskType;

    taskType = new GraphQLObjectType({
      name: 'Task',
      description: 'A task',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt)
        },
        title: {
          type: GraphQLString
        }
      }
    });

    userType = new GraphQLObjectType({
      name: 'User',
      description: 'A user',
      fields: {
        id: {
          type: new GraphQLNonNull(GraphQLInt),
        },
        name: {
          type: GraphQLString,
        },
        tasks: {
          type: new GraphQLObjectType({
            name: 'Tasks',
            fields: {
              nodes: {
                type: new GraphQLList(taskType),
                resolve: resolver(User.Tasks)
              }
            }
          }),
          resolve: (function () {
            let $resolver;

            $resolver = function (source) {
              return source;
            };

            $resolver.$passthrough = true;

            return $resolver;
          }())
        }
      }
    });

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              }
            },
            resolve: resolver(User)
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name,
            tasks {
              nodes {
                title
              }
              nodes {
                id
              }
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks.nodes).to.have.length.above(0);
        user.tasks.nodes.forEach(function (task) {
          expect(task.title).to.be.ok;
          expect(task.id).to.be.ok;
        });
      });
    });
  });

  it('should resolve an array result with a single model and limit', () => {
    return graphql({
      schema,
      source: `
        {
          users(limit: 1) {
            name
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(1);
    });
  });

  it('should resolve a plain result with a single hasMany association', () => {
    const user = state.userB;

    return graphql({
      schema,
      source: `
        {
          user(id: ${user.id}) {
            name
            tasks {
              title
              taskVirtual
            }
          }
        }
      `,
      contextValue: {
        yolo: 'swag'
      },
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.user.name).to.equal(user.name);

      expect(result.data.user.tasks).to.have.length.above(0);
      // As the order of user.tasks is nondeterministic, we only assert on equal members
      // of both the user's tasks and the tasks the graphql query responded with.
      const userTasks = user.tasks.map(task => ({title: task.title, taskVirtual: 'tasktask'}));
      expect(result.data.user.tasks).to.deep.have.members(userTasks);
    });

  });

  it('should resolve a plain result with a single limited hasMany association', () => {
    const user = state.userB;

    return graphql({
      schema,
      source: `
        {
          user(id: ${user.id}) {
            name
            tasks(limit: 1) {
              title
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.user.tasks).to.have.length(1);
    });
  });

  it('should resolve a array result with a single hasMany association', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users(order: "id") {
            name
            tasks(order: "id") {
              title
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).length.to.be.above(0);
      });

      expect(result.data).to.deep.equal({
        users: users.map(function (user) {
          return {
            name: user.name,
            tasks: user.tasks.map(task => ({title: task.title}))
          };
        })
      });
    });
  });

  it('should resolve a array result with a single limited hasMany association', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            name
            tasks(limit: 1) {
              title
            }
          }
        }
      `
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).to.have.length(1);
      });
    });
  });

  it('should resolve a array result with a single limited hasMany association with a nested belongsTo relation', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            tasks(limit: 2) {
              title
              project {
                name
              }
            }
          }
        }
      `
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).to.have.length(2);
        user.tasks.forEach(function (task) {
          expect(task.project.name).to.be.ok;
        });
      });
    });
  });

  it('should resolve a array result with a single hasMany association with a nested belongsTo relation', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            tasks {
              title
              project {
                name
              }
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).length.to.be.above(0);
        user.tasks.forEach(function (task) {
          expect(task.project.name).to.be.ok;
        });
      });
    });
  });

  it('should resolve a array result with a single hasMany association' +
     'with a nested belongsTo relation with a nested hasMany relation', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            tasks {
              title
              project {
                name
                labels {
                  name
                }
              }
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).length.to.be.above(0);
        user.tasks.forEach(function (task) {
          expect(task.project.name).to.be.ok;

          expect(task.project.labels).length.to.be.above(0);
          task.project.labels.forEach(function (label) {
            expect(label.name).to.be.ok;
          });
        });
      });
    });
  });

  it('should resolve a array result with a single limited hasMany association with a before filter', () => {
    const users = state.users;

    return graphql({
      schema,
      source: `
        {
          users {
            tasks(first: 2) {
              title
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users.length).to.equal(users.length);
      result.data.users.forEach(function (user) {
        expect(user.tasks).to.have.length(2);
      });
    });
  });

  it('should not call association getter if user manually included', () => {
    vi.spyOn(Task, 'findAll');
    vi.spyOn(User, 'findAll');

    const schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            resolve: resolver(User, {
              before: function (options) {
                options.include = [User.Tasks];
                options.order = [
                  ['id'],
                  [{ model: Task, as: 'tasks' }, 'id', 'ASC']
                ];
                return options;
              }
            })
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            tasks {
              title
            }
          }
        }
      `,
    }).then(result => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(vi.mocked(Task.findAll)).not.toHaveBeenCalled();
      expect(vi.mocked(User.findAll)).toHaveBeenCalledTimes(1);
      expect(vi.mocked(User.findAll).mock.calls[0][0].include).to.have.length(1);
      expect(
        vi.mocked(User.findAll).mock.calls[0][0].include[0].name
      ).to.equal(User.Tasks.name);

      result.data.users.forEach(function (user) {
        expect(user.tasks).to.have.length.above(0);
      });

      expect(result.data).to.deep.equal({
        users: state.users.map(function (user) {
          return {
            tasks: user.tasks.map(task => ({title: task.title}))
          };
        })
      });
    });
  });

  it('should allow async before and after', () => {
    let users = state.users
      , schema;

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLList(userType),
            args: {
              limit: {
                type: GraphQLInt
              },
              order: {
                type: GraphQLString
              }
            },
            resolve: resolver(User, {
              before: function (options) {
                return Promise.resolve(options);
              },
              after: async function (result) {
                await delay(100);
                return result.map(function () {
                  return {
                    name: 'Delayed!'
                  };
                });
              }
            })
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(users.length);
      result.data.users.forEach(function (user) {
        expect(user.name).to.equal('Delayed!');
      });
    });
  });

  it('supports models and required filters in the preferred options object', async () => {
    const before = vi.fn((options) => options);
    const after = vi.fn((result) => result);
    const resolveUsers = resolver(User, {
      models: {
        [User.name]: User
      },
      requiredFilters: ['id'],
      before,
      after
    });
    const info = {
      returnType: new GraphQLList(userType),
      variableValues: {}
    };
    let missingFilterError;

    try {
      await resolveUsers(null, {}, {}, info);
    } catch (error) {
      missingFilterError = error;
    }

    expect(missingFilterError).to.be.instanceOf(Error);
    expect(missingFilterError.message).to.match(/Filter id is missing/);

    const result = await resolveUsers(
      null,
      { where: { id: state.userA.id } },
      {},
      info
    );

    expect(result).to.have.length(1);
    expect(result[0].id).to.equal(state.userA.id);
    expect(before).toHaveBeenCalledTimes(1);
    expect(after).toHaveBeenCalledTimes(1);
  });

  it('rejects positional resolver options with migration guidance', () => {
    const before = vi.fn((options) => options);
    const after = vi.fn((result) => result);
    const models = {
      [User.name]: User
    };
    const message =
      'resolver() accepts at most two arguments. Use resolver(target, { models, requiredFilters, ...options }).';

    expect(() => resolver(User, models, ['id'])).to.throw(message);
    expect(() =>
      resolver(User, models, ['id'], {
        before,
        after
      })
    ).to.throw(message);
    expect(before).not.toHaveBeenCalled();
    expect(after).not.toHaveBeenCalled();
  });

  it('should resolve args from array to before', () => {
    const user = state.userB;

    return graphql({
      schema,
      source: `
        {
          user(id: ${user.get('id')}) {
            tasksByIds(ids: [${user.tasks[0].get('id')}]) {
              id
            }
          }
        }
      `,
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.user.tasksByIds.length).to.equal(1);
    });
  });

  it('should resolve query variables inside where parameter', () => {
    return graphql({
      schema,
      source: `
        query($where: SequelizeJSON) {
          users(where: $where) {
            id
          }
        }
      `,
      variableValues: {
        where: '{"name": {"like": "a%"}}',
      },
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users[0].id).to.equal(2);
      expect(result.data.users.length).to.equal(1);
    });
  });

  it('should resolve query variables inside where parameter', () => {
    return graphql({
      schema,
      source: `
        query($name: String) {
          users(where: {name: {like: $name}}) {
            id
          }
        }
      `,
      variableValues: {name: 'a%'}
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users[0].id).to.equal(2);
      expect(result.data.users.length).to.equal(1);
    });
  });

  it('should allow list queries set as NonNullable', () => {
    let user = state.userA
      , schema;

    schema = new GraphQLSchema({
      query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
          users: {
            type: new GraphQLNonNull(new GraphQLList(userType)),
            resolve: resolver(User, {
              before: function (options, args, { name }) {
                options.where = options.where || {};
                options.where.name = name;
                return options;
              }
            })
          }
        }
      })
    });

    return graphql({
      schema,
      source: `
        {
          users {
            name
          }
        }
      `,
      contextValue: {
        name: user.name,
      },
    }).then((result) => {
      if (result.errors) throw new Error(result.errors[0].stack);

      expect(result.data.users).to.have.length(1);
      expect(result.data.users[0].name).to.equal(user.name);
    });
  });

  describe('update operation', function () {
    let UpdateUser;
    let updateInfo;

    beforeAll(async function () {
      UpdateUser = sequelize.define('resolverUpdateUser', {
        name: Sequelize.STRING,
        status: Sequelize.STRING,
        scheduledAt: Sequelize.DATE
      }, {
        timestamps: false
      });
      markFilterable(UpdateUser, 'id');
      await UpdateUser.sync({ force: true });

      updateInfo = {
        returnType: new GraphQLObjectType({
          name: 'ResolverUpdateUser',
          fields: {
            id: { type: GraphQLInt },
            name: { type: GraphQLString },
            status: { type: GraphQLString }
          }
        }),
        variableValues: {}
      };
    });

    beforeEach(async function () {
      await UpdateUser.destroy({ where: {} });
      state.updateUser = await UpdateUser.create({
        name: 'before-update',
        status: 'active',
        scheduledAt: new Date('2026-07-31T12:34:56.000Z')
      });
    });

    it('updates a direct model through Sequelize', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });

      await resolveUpdate(
        null,
        {
          where: { id: state.updateUser.id },
          data: { name: 'after-update' }
        },
        {},
        updateInfo
      );

      const persisted = await UpdateUser.findByPk(state.updateUser.id);
      expect(persisted.name).to.equal('after-update');
      expect(persisted.status).to.equal('active');
    });

    it('updates a model returned by a target thunk', async function () {
      const resolveUpdate = resolver(
        async () => UpdateUser,
        { operation: 'update' }
      );

      const result = await resolveUpdate(
        null,
        {
          where: { id: state.updateUser.id },
          data: { status: 'inactive' }
        },
        {},
        updateInfo
      );

      expect(result.status).to.equal('inactive');
    });

    it('treats update values as bound data rather than SQL', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });
      const unsafeValue = "quoted'value, status = 'changed' --";

      const result = await resolveUpdate(
        null,
        {
          where: { id: state.updateUser.id },
          data: { name: unsafeValue }
        },
        {},
        updateInfo
      );

      expect(result.name).to.equal(unsafeValue);
      expect(result.status).to.equal('active');
    });

    it('propagates transaction and compatible find options to update', async function () {
      const transaction = await sequelize.transaction();
      const logging = vi.fn();
      const update = vi.spyOn(UpdateUser, 'update');
      const resolveUpdate = resolver(UpdateUser, {
        operation: 'update',
        before(options) {
          options.transaction = transaction;
          options.logging = logging;
          options.paranoid = false;
          options.hooks = false;
          options.silent = true;
          options.offset = 0;
          options.order = [['id', 'DESC']];
          options.include = [];

          return options;
        }
      });

      try {
        const result = await resolveUpdate(
          null,
          {
            where: { id: state.updateUser.id },
            data: { name: 'inside-transaction' }
          },
          {},
          updateInfo
        );
        const updateOptions = update.mock.calls[0][1];

        expect(result.name).to.equal('inside-transaction');
        expect(updateOptions.transaction).to.equal(transaction);
        expect(updateOptions.logging).to.equal(logging);
        expect(updateOptions.paranoid).to.equal(false);
        expect(updateOptions.hooks).to.equal(false);
        expect(updateOptions.silent).to.equal(true);
        expect(updateOptions).to.not.have.property('attributes');
        expect(updateOptions).to.not.have.property('include');
        expect(updateOptions).to.not.have.property('offset');
        expect(updateOptions).to.not.have.property('order');
      } finally {
        update.mockRestore();
        await transaction.rollback();
      }

      const persisted = await UpdateUser.findByPk(state.updateUser.id);
      expect(persisted.name).to.equal('before-update');
    });

    it('returns the row read after the update', async function () {
      const after = vi.fn((result) => result);
      const resolveUpdate = resolver(UpdateUser, {
        operation: 'update',
        after
      });

      const result = await resolveUpdate(
        null,
        {
          where: { id: state.updateUser.id },
          data: { name: 'read-after-update' }
        },
        {},
        updateInfo
      );

      expect(result.name).to.equal('read-after-update');
      expect(after).toHaveBeenCalledTimes(1);
      expect(after.mock.calls[0][0]).to.equal(result);
    });

    it('does not limit the rows changed by an update', async function () {
      await state.updateUser.update({ name: 'limit-one' });
      await UpdateUser.bulkCreate([
        { name: 'limit-two', status: 'active' },
        { name: 'limit-three', status: 'active' },
        { name: 'limit-four', status: 'active' }
      ]);
      const resolveUpdate = resolver(UpdateUser, {
        list: true,
        operation: 'update',
        before(options) {
          options.where = { name: { [Op.like]: 'limit-%' } };

          return options;
        }
      });

      const result = await resolveUpdate(
        null,
        { limit: 2, data: { status: 'updated' } },
        {},
        { ...updateInfo, returnType: new GraphQLList(updateInfo.returnType) }
      );
      const persisted = await UpdateUser.findAll({
        attributes: ['status'],
        order: [['id', 'ASC']],
        raw: true
      });

      expect(result).to.have.length(2);
      expect(result.map((row) => row.status)).to.deep.equal([
        'updated',
        'updated'
      ]);
      expect(persisted.map((row) => row.status)).to.deep.equal([
        'updated',
        'updated',
        'updated',
        'updated'
      ]);
    });

    it('returns rows when the update changes a filtered attribute', async function () {
      const resolveUpdate = resolver(UpdateUser, {
        operation: 'update',
        before(options) {
          options.where = { name: 'before-update' };

          return options;
        }
      });

      const result = await resolveUpdate(
        null,
        { data: { name: 'after-update' } },
        {},
        updateInfo
      );

      expect(result.id).to.equal(state.updateUser.id);
      expect(result.name).to.equal('after-update');
    });

    it('returns a keyless row when its filtered attribute changes', async function () {
      const KeylessUpdate = sequelize.define('resolverKeylessUpdate', {
        code: Sequelize.STRING,
        status: Sequelize.STRING
      });
      KeylessUpdate.removeAttribute('id');
      markFilterable(KeylessUpdate, 'code');
      await KeylessUpdate.sync({ force: true });
      await KeylessUpdate.bulkCreate([
        { code: 'keyless-before', status: 'target' },
        { code: 'other-row', status: 'untouched' }
      ]);
      await delay(10);
      const keylessInfo = {
        returnType: new GraphQLObjectType({
          name: 'ResolverKeylessUpdate',
          fields: {
            code: { type: GraphQLString },
            status: { type: GraphQLString }
          }
        }),
        variableValues: {}
      };

      const result = await resolver(KeylessUpdate, {
        operation: 'update'
      })(
        null,
        {
          where: { code: 'keyless-before' },
          data: { code: 'keyless-after' }
        },
        {},
        keylessInfo
      );

      expect(result.code).to.equal('keyless-after');
      expect(result.status).to.equal('target');
      expect(await KeylessUpdate.findOne({
        where: { code: 'other-row' }
      })).to.have.property('status', 'untouched');
    });

    it('uses updated composite primary keys to read changed rows', async function () {
      const CompositeUpdate = sequelize.define('resolverCompositeUpdate', {
        tenantId: { primaryKey: true, type: Sequelize.INTEGER },
        userId: { primaryKey: true, type: Sequelize.INTEGER },
        status: Sequelize.STRING
      }, {
        timestamps: false
      });
      await CompositeUpdate.sync({ force: true });
      await CompositeUpdate.bulkCreate([
        { tenantId: 1, userId: 1, status: 'active' },
        { tenantId: 2, userId: 1, status: 'active' }
      ]);
      const result = await resolver(CompositeUpdate, {
        operation: 'update'
      })(
        null,
        {
          where: { tenantId: 1, userId: 1 },
          data: { tenantId: 9, status: 'updated' }
        },
        {},
        updateInfo
      );

      expect(result.tenantId).to.equal(9);
      expect(result.userId).to.equal(1);
      expect(result.status).to.equal('updated');
      expect(await CompositeUpdate.findOne({
        where: { tenantId: 2, userId: 1 }
      })).to.have.property('status', 'active');
    });

    it('updates through a Date-valued attribute filter', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });

      const result = await resolveUpdate(
        null,
        {
          where: { scheduledAt: state.updateUser.scheduledAt },
          data: { status: 'date-filtered' }
        },
        {},
        updateInfo
      );

      expect(result.status).to.equal('date-filtered');
      const persisted = await UpdateUser.findByPk(state.updateUser.id);
      expect(persisted.status).to.equal('date-filtered');
    });

    it('updates through a Sequelize where expression', async function () {
      const updateUser = state.updateUser;
      const resolveUpdate = resolver(UpdateUser, {
        operation: 'update',
        before(options) {
          options.where = Sequelize.where(
            Sequelize.col('id'),
            updateUser.id
          );

          return options;
        }
      });

      const result = await resolveUpdate(
        null,
        {
          where: { id: updateUser.id },
          data: { status: 'expression-filtered' }
        },
        {},
        updateInfo
      );

      expect(result.status).to.equal('expression-filtered');
    });

    it('updates through a valid logical object predicate', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });

      const result = await resolveUpdate(
        null,
        {
          where: {
            [Op.and]: [
              { id: state.updateUser.id },
              { scheduledAt: state.updateUser.scheduledAt }
            ]
          },
          data: { status: 'logical-object-filtered' }
        },
        {},
        updateInfo
      );

      expect(result.status).to.equal('logical-object-filtered');
    });

    it('updates through a logical Sequelize expression', async function () {
      const updateUser = state.updateUser;
      const resolveUpdate = resolver(UpdateUser, {
        operation: 'update',
        before(options) {
          options.where = {
            [Op.and]: [
              Sequelize.where(
                Sequelize.col('id'),
                updateUser.id
              )
            ]
          };

          return options;
        }
      });

      const result = await resolveUpdate(
        null,
        {
          where: { id: updateUser.id },
          data: { status: 'logical-expression-filtered' }
        },
        {},
        updateInfo
      );

      expect(result.status).to.equal('logical-expression-filtered');
    });

    const ineffectiveWhereFactories = [
      ['a direct empty Sequelize literal', () => Sequelize.literal('')],
      [
        'a nested empty Sequelize literal',
        () => ({ [Op.and]: [Sequelize.literal('')] })
      ],
      [
        'an unknown symbol-only key',
        () => ({ [Symbol('unknown-where-key')]: true })
      ],
      [
        'a non-enumerable predicate',
        (updateUser) => {
          const where = {};
          Object.defineProperty(where, 'id', {
            enumerable: false,
            value: updateUser.id
          });

          return where;
        }
      ],
      ['a sparse and array', () => ({ [Op.and]: new Array(1) })],
      ['a sparse or array', () => ({ [Op.or]: new Array(1) })],
      ['a sparse not array', () => ({ [Op.not]: new Array(1) })]
    ];

    ineffectiveWhereFactories.forEach(([description, createWhere]) => {
      it(`rejects ${description} without changing rows`, async function () {
        const updateUser = state.updateUser;
        await UpdateUser.create({
          name: 'second-user',
          status: 'second-active',
          scheduledAt: new Date('2026-07-30T12:34:56.000Z')
        });
        const beforeRows = await UpdateUser.findAll({
          attributes: ['id', 'status'],
          order: [['id', 'ASC']],
          raw: true
        });
        const resolveUpdate = resolver(UpdateUser, {
          operation: 'update',
          before(options) {
            options.where = createWhere(updateUser);

            return options;
          }
        });
        let updateError;

        try {
          await resolveUpdate(
            null,
            {
              where: { id: updateUser.id },
              data: { status: 'must-not-update' }
            },
            {},
            updateInfo
          );
        } catch (error) {
          updateError = error;
        }

        const afterRows = await UpdateUser.findAll({
          attributes: ['id', 'status'],
          order: [['id', 'ASC']],
          raw: true
        });

        expect(updateError).to.be.instanceOf(Error);
        expect(updateError.message).to.equal(
          'No where filter provided to perform an update.'
        );
        expect(afterRows).to.deep.equal(beforeRows);
      });
    });

    const invalidLogicalEntries = [
      ['null', null],
      ['false', false],
      ['zero', 0],
      ['an empty string', ''],
      ['a Date', new Date('2026-07-31T12:34:56.000Z')],
      ['an empty object', {}],
      ['an empty array', []]
    ];
    const logicalOperators = [
      ['and', Op.and],
      ['or', Op.or],
      ['not', Op.not]
    ];

    logicalOperators.forEach(([operatorName, operator]) => {
      invalidLogicalEntries.forEach(([entryName, invalidEntry]) => {
        it(`rejects ${operatorName} arrays containing ${entryName}`, async function () {
          await UpdateUser.create({
            name: 'second-user',
            status: 'second-active',
            scheduledAt: new Date('2026-07-30T12:34:56.000Z')
          });
          const beforeRows = await UpdateUser.findAll({
            attributes: ['id', 'status'],
            order: [['id', 'ASC']],
            raw: true
          });
          const resolveUpdate = resolver(UpdateUser, {
            operation: 'update'
          });
          let updateError;

          try {
            await resolveUpdate(
              null,
              {
                where: { [operator]: [invalidEntry] },
                data: { status: 'must-not-update' }
              },
              {},
              updateInfo
            );
          } catch (error) {
            updateError = error;
          }

          const afterRows = await UpdateUser.findAll({
            attributes: ['id', 'status'],
            order: [['id', 'ASC']],
            raw: true
          });

          expect(updateError).to.be.instanceOf(Error);
          expect(updateError.message).to.equal(
            'No where filter provided to perform an update.'
          );
          expect(afterRows).to.deep.equal(beforeRows);
        });
      });
    });

    it('rejects missing, empty, and non-plain update data', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });
      const args = { where: { id: state.updateUser.id } };

      await expect(
        resolveUpdate(null, args, {}, updateInfo)
      ).rejects.toThrow('No data provided to perform an update.');
      await expect(
        resolveUpdate(null, { ...args, data: {} }, {}, updateInfo)
      ).rejects.toThrow('No data provided to perform an update.');
      await expect(
        resolveUpdate(null, { ...args, data: [] }, {}, updateInfo)
      ).rejects.toThrow('Update data must be a plain object.');
      await expect(
        resolveUpdate(null, { ...args, data: new Date() }, {}, updateInfo)
      ).rejects.toThrow('Update data must be a plain object.');
    });

    it('rejects unknown update attributes', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });

      await expect(
        resolveUpdate(
          null,
          {
            where: { id: state.updateUser.id },
            data: { missingAttribute: 'value' }
          },
          {},
          updateInfo
        )
      ).rejects.toThrow('Unknown update attribute: missingAttribute');
    });

    it('requires a meaningful update where filter', async function () {
      const resolveUpdate = resolver(UpdateUser, { operation: 'update' });
      const emptyFilters = [
        {},
        { id: {} },
        { [Op.and]: [] }
      ];

      for (const where of emptyFilters) {
        await expect(
          resolveUpdate(
            null,
            { where, data: { name: 'unscoped-update' } },
            {},
            updateInfo
          )
        ).rejects.toThrow('No where filter provided to perform an update.');
      }
    });

    it('rejects direct and thunked association update targets', async function () {
      expect(() =>
        resolver(User.Tasks, { operation: 'update' })
      ).to.throw('Update operation requires a model target.');

      const resolveUpdate = resolver(
        () => User.Tasks,
        { operation: 'update' }
      );

      await expect(
        resolveUpdate(
          state.userA,
          { where: { id: 1 }, data: { title: 'unsupported' } },
          {},
          { ...updateInfo, returnType: taskType }
        )
      ).rejects.toThrow('Update operation requires a model target.');
    });

    it('rejects joined updates', async function () {
      const resolveUpdate = resolver(User, {
        operation: 'update',
        models: { tasks: Task }
      });

      await expect(
        resolveUpdate(
          null,
          {
            where: { tasks: { title: 'joined' } },
            data: { name: 'unsupported' }
          },
          {},
          { ...updateInfo, returnType: userType }
        )
      ).rejects.toThrow('Joined updates are not supported.');
    });
  });

  describe('default scope attributes', function () {
    let ArrayScopedUser;
    let ObjectScopedUser;
    let arrayInfo;
    let objectInfo;

    beforeAll(async function () {
      ArrayScopedUser = sequelize.define('resolverArrayScopedUser', {
        name: Sequelize.STRING,
        secret: Sequelize.STRING
      }, {
        defaultScope: {
          attributes: ['id', 'name']
        },
        timestamps: false
      });
      ObjectScopedUser = sequelize.define('resolverObjectScopedUser', {
        name: Sequelize.STRING,
        status: Sequelize.STRING,
        secret: Sequelize.STRING
      }, {
        defaultScope: {
          attributes: {
            exclude: ['secret'],
            include: [['name', 'displayName']]
          }
        },
        timestamps: false
      });
      markFilterable(ArrayScopedUser, 'id');
      markFilterable(ObjectScopedUser, 'id');
      await ArrayScopedUser.sync({ force: true });
      await ObjectScopedUser.sync({ force: true });

      arrayInfo = {
        returnType: new GraphQLObjectType({
          name: 'ResolverArrayScopedUser',
          fields: {
            id: { type: GraphQLInt },
            name: { type: GraphQLString }
          }
        }),
        variableValues: {}
      };
      objectInfo = {
        returnType: new GraphQLObjectType({
          name: 'ResolverObjectScopedUser',
          fields: {
            id: { type: GraphQLInt },
            name: { type: GraphQLString },
            status: { type: GraphQLString },
            displayName: { type: GraphQLString }
          }
        }),
        variableValues: {}
      };
    });

    beforeAll(async function () {
      await ArrayScopedUser.create({ name: 'array-visible', secret: 'hidden' });
      await ObjectScopedUser.create({
        name: 'object-visible',
        status: 'active',
        secret: 'hidden'
      });
    });

    it('preserves an official array attribute projection', async function () {
      const findOne = vi.spyOn(ArrayScopedUser, 'findOne');

      try {
        const result = await resolver(ArrayScopedUser)(null, {}, {}, arrayInfo);

        expect(result.name).to.equal('array-visible');
        expect(result.get('secret')).to.equal(undefined);
        expect(findOne.mock.calls[0][0].attributes).to.deep.equal([
          'id',
          'name'
        ]);
      } finally {
        findOne.mockRestore();
      }
    });

    it('preserves include, exclude, and aliases in object projections', async function () {
      const findOne = vi.spyOn(ObjectScopedUser, 'findOne');

      try {
        const result = await resolver(ObjectScopedUser)(
          null,
          {},
          {},
          objectInfo
        );

        expect(result.name).to.equal('object-visible');
        expect(result.status).to.equal('active');
        expect(result.get('secret')).to.equal(undefined);
        expect(result.get('displayName')).to.equal('object-visible');
        expect(findOne.mock.calls[0][0].attributes).to.deep.equal({
          exclude: ['secret'],
          include: [['name', 'displayName']]
        });
      } finally {
        findOne.mockRestore();
      }
    });

    it('supports object attribute projections on Relay connections', async function () {
      const connection = createConnection({
        name: 'ResolverObjectScopedUsers',
        nodeType: objectInfo.returnType,
        target: ObjectScopedUser
      });
      const scopedSchema = new GraphQLSchema({
        query: new GraphQLObjectType({
          name: 'ResolverObjectScopedQuery',
          fields: {
            users: {
              args: connection.connectionArgs,
              resolve: connection.resolve,
              type: connection.connectionType
            }
          }
        })
      });

      const result = await graphql({
        schema: scopedSchema,
        source: `
          query {
            users(first: 1) {
              edges {
                node {
                  name
                  status
                }
              }
            }
          }
        `
      });

      expect(result.errors).to.equal(undefined);
      expect(result.data).to.deep.equal({
        users: {
          edges: [{
            node: {
              name: 'object-visible',
              status: 'active'
            }
          }]
        }
      });
    });
  });

  describe('resolver-local count context', function () {
    let CountAlpha;
    let CountBeta;
    let alphaInfo;
    let betaInfo;

    beforeAll(async function () {
      CountAlpha = sequelize.define('resolverCountAlpha', {
        category: Sequelize.STRING
      }, {
        timestamps: false
      });
      CountBeta = sequelize.define('resolverCountBeta', {
        category: Sequelize.STRING
      }, {
        timestamps: false
      });
      await CountAlpha.sync({ force: true });
      await CountBeta.sync({ force: true });
      await CountAlpha.bulkCreate([
        { category: 'included' },
        { category: 'included' },
        { category: 'excluded' }
      ]);
      await CountBeta.bulkCreate([
        { category: 'included' },
        { category: 'included' },
        { category: 'included' },
        { category: 'excluded' }
      ]);

      alphaInfo = {
        returnType: new GraphQLList(new GraphQLObjectType({
          name: 'ResolverCountAlpha',
          fields: {
            category: { type: GraphQLString }
          }
        })),
        variableValues: {}
      };
      betaInfo = {
        returnType: new GraphQLList(new GraphQLObjectType({
          name: 'ResolverCountBeta',
          fields: {
            category: { type: GraphQLString }
          }
        })),
        variableValues: {}
      };
    });

    it('preserves caller-owned model and where context fields', async function () {
      const sharedContext = {
        model: 'v2-api',
        where: 'tenant-42'
      };
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after: async (result, _args, context) => {
          expect(context.model).to.equal('v2-api');
          expect(context.where).to.equal('tenant-42');
          expect(await context.count()).to.equal(3);

          return result;
        }
      });

      await resolveAlpha(null, {}, sharedContext, alphaInfo);

      expect(sharedContext.model).to.equal('v2-api');
      expect(sharedContext.where).to.equal('tenant-42');
    });

    it('isolates count closures across concurrent sibling after hooks', async function () {
      const sharedContext = {};
      let arrived = 0;
      let release;
      const bothAfterHooksArrived = new globalThis.Promise((resolve) => {
        release = resolve;
      });
      const after = async (_result, _args, context) => {
        arrived += 1;
        if (arrived === 2) {
          release();
        }
        await bothAfterHooksArrived;

        return { count: await context.count() };
      };
      const resolveAlpha = resolver(CountAlpha, { list: true, after });
      const resolveBeta = resolver(CountBeta, { list: true, after });

      const [alphaContext, betaContext] = await Promise.all([
        resolveAlpha(
          null,
          { where: { category: 'included' } },
          sharedContext,
          alphaInfo
        ),
        resolveBeta(
          null,
          { where: { category: 'included' } },
          sharedContext,
          betaInfo
        )
      ]);

      expect(alphaContext).to.deep.equal({ count: 2 });
      expect(betaContext).to.deep.equal({ count: 3 });
      expect(await sharedContext.count()).to.equal(3);
    });

    it('passes the original private-field context to after hooks', async function () {
      class PrivateFieldContext {
        #value = 'private-context';

        /**
         * Read the private value through a private method.
         *
         * @return {String} private context value
         */
        readValue() {
          return this.#readValue();
        }

        /**
         * Read the private field using the class brand.
         *
         * @return {String} private context value
         */
        #readValue() {
          return this.#value;
        }
      }

      const context = new PrivateFieldContext();
      let afterContext;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(_result, _args, localContext) {
          afterContext = localContext;

          return localContext.readValue();
        }
      });

      const result = await resolveAlpha(null, {}, context, alphaInfo);

      expect(afterContext).to.equal(context);
      expect(result).to.equal('private-context');
    });

    it('passes the original Map context to after hooks', async function () {
      const context = new Map([['existing', 'map-context']]);
      let afterContext;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(_result, _args, localContext) {
          afterContext = localContext;
          localContext.set('added', 'map-added');

          return localContext.get('existing');
        }
      });

      const result = await resolveAlpha(null, {}, context, alphaInfo);

      expect(afterContext).to.equal(context);
      expect(result).to.equal('map-context');
      expect(context.get('added')).to.equal('map-added');
    });

    it('passes the original Set context to after hooks', async function () {
      const context = new Set(['set-context']);
      let afterContext;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(_result, _args, localContext) {
          afterContext = localContext;
          localContext.add('set-added');

          return localContext.has('set-context');
        }
      });

      const result = await resolveAlpha(null, {}, context, alphaInfo);

      expect(afterContext).to.equal(context);
      expect(result).to.equal(true);
      expect(context.has('set-added')).to.equal(true);
    });

    it('passes the original Date context to after hooks', async function () {
      const context = new Date('2020-01-02T03:04:05.000Z');
      let afterContext;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(_result, _args, localContext) {
          afterContext = localContext;

          return localContext.getTime();
        }
      });

      const result = await resolveAlpha(null, {}, context, alphaInfo);

      expect(afterContext).to.equal(context);
      expect(result).to.equal(context.getTime());
    });

    it('keeps compatible query options in resolver-local counts', async function () {
      const transaction = await sequelize.transaction();
      const logging = vi.fn();
      const count = vi.spyOn(CountAlpha, 'count');
      const context = {};
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        before(options) {
          options.transaction = transaction;
          options.logging = logging;
          options.paranoid = false;
          options.limit = 1;
          options.offset = 0;
          options.order = [['id', 'ASC']];
          options.include = [];
          options.customCountOption = 'preserved';

          return options;
        },
        after: async (_result, _args, localContext) => {
          return localContext.count();
        }
      });

      try {
        const result = await resolveAlpha(
          null,
          { where: { category: 'included' } },
          context,
          alphaInfo
        );
        const countOptions = count.mock.calls[0][0];

        expect(result).to.equal(2);
        expect(countOptions.transaction).to.equal(transaction);
        expect(countOptions.logging).to.equal(logging);
        expect(countOptions.paranoid).to.equal(false);
        expect(countOptions.include).to.deep.equal([]);
        expect(countOptions.where).to.deep.equal({ category: 'included' });
        expect(countOptions.customCountOption).to.equal('preserved');
        expect(countOptions.distinct).to.equal(true);
        expect(countOptions).to.not.have.property('attributes');
        expect(countOptions).to.not.have.property('limit');
        expect(countOptions).to.not.have.property('offset');
        expect(countOptions).to.not.have.property('order');
      } finally {
        count.mockRestore();
        await transaction.rollback();
      }
    });

    it('forwards after-hook context writes to the shared context', async function () {
      const replacementCount = vi.fn().mockResolvedValue(41);
      const extensionValue = { source: 'after-hook' };
      const sharedContext = { existingField: 'existing' };
      let hookKeys;
      let hookHasExtension;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(result, _args, localContext) {
          localContext.count = replacementCount;
          localContext.extensionField = extensionValue;

          expect(localContext.count).to.equal(replacementCount);
          expect(localContext.extensionField).to.equal(extensionValue);
          hookKeys = Object.keys(localContext);
          hookHasExtension = 'extensionField' in localContext;

          return result;
        }
      });

      await resolveAlpha(
        null,
        { where: { category: 'included' } },
        sharedContext,
        alphaInfo
      );

      expect(sharedContext.count).to.equal(replacementCount);
      expect(sharedContext.extensionField).to.equal(extensionValue);
      expect(hookHasExtension).to.equal(true);
      expect(hookKeys).to.have.members([
        'existingField',
        'count',
        'extensionField'
      ]);
      expect(await sharedContext.count()).to.equal(41);
    });

    it('reinstalls metadata accessors after native replacement and deletion', async function () {
      const replacementCount = vi.fn().mockResolvedValue(41);
      const sharedContext = {};
      let hookCalls = 0;
      let secondSnapshot;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        async after(result, _args, localContext) {
          hookCalls += 1;
          expect(localContext).to.equal(sharedContext);

          if (hookCalls === 1) {
            Object.defineProperty(localContext, 'count', {
              configurable: true,
              enumerable: false,
              value: replacementCount,
              writable: true
            });
            return result;
          }

          secondSnapshot = {
            count: await localContext.count(),
            countDescriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'count'
            )
          };

          return result;
        }
      });

      await resolveAlpha(
        null,
        { where: { category: 'excluded' } },
        sharedContext,
        alphaInfo
      );

      expect(sharedContext.count).to.equal(replacementCount);

      await resolveAlpha(
        null,
        { where: { category: 'included' } },
        sharedContext,
        alphaInfo
      );

      expect(secondSnapshot.count).to.equal(2);
      expect(secondSnapshot.countDescriptor).to.include({
        configurable: true,
        enumerable: true
      });
      expect(secondSnapshot.countDescriptor.get).to.be.a('function');
      expect(secondSnapshot.countDescriptor.set).to.be.a('function');
      expect(await sharedContext.count()).to.equal(2);
    });

    it('keeps native fallback behavior for non-configurable metadata', async function () {
      const fixedCount = vi.fn().mockResolvedValue(91);
      const sharedContext = {};
      Object.defineProperty(sharedContext, 'count', {
        configurable: false,
        enumerable: true,
        value: fixedCount,
        writable: false
      });
      let afterContext;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(_result, _args, localContext) {
          afterContext = localContext;

          return localContext.count();
        }
      });

      const result = await resolveAlpha(
        null,
        { where: { category: 'included' } },
        sharedContext,
        alphaInfo
      );

      expect(afterContext).to.equal(sharedContext);
      expect(result).to.equal(91);
      expect(sharedContext.count).to.equal(fixedCount);
      expect(Object.getOwnPropertyDescriptor(sharedContext, 'count')).to
        .deep.equal({
          configurable: false,
          enumerable: true,
          value: fixedCount,
          writable: false
        });
    });

    it('coordinates complete after-hook context mutation semantics', async function () {
      const definedCount = vi.fn().mockResolvedValue(73);
      const sharedContext = { existingField: 'existing' };
      let mutationSnapshot;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(result, _args, localContext) {
          Object.defineProperty(localContext, 'count', {
            configurable: true,
            enumerable: false,
            value: definedCount,
            writable: true
          });
          Object.defineProperty(localContext, 'permanentExtension', {
            configurable: false,
            enumerable: true,
            value: 'permanent',
            writable: false
          });
          localContext.temporaryExtension = 'temporary';

          expect(delete localContext.temporaryExtension).to.equal(true);
          expect(() => {
            Object.defineProperty(localContext, 'permanentExtension', {
              value: 'changed'
            });
          }).to.throw(TypeError);
          expect(() => {
            delete localContext.permanentExtension;
          }).to.throw(TypeError);

          mutationSnapshot = {
            count: localContext.count,
            countDescriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'count'
            ),
            hasPermanentExtension: 'permanentExtension' in localContext,
            hasTemporaryExtension: 'temporaryExtension' in localContext,
            keys: Reflect.ownKeys(localContext),
            permanentDescriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'permanentExtension'
            ),
            permanentExtension: localContext.permanentExtension,
            temporaryExtension: localContext.temporaryExtension
          };

          return result;
        }
      });

      await resolveAlpha(
        null,
        { where: { category: 'included' } },
        sharedContext,
        alphaInfo
      );

      expect(mutationSnapshot.count).to.equal(definedCount);
      expect(mutationSnapshot.temporaryExtension).to.equal(undefined);
      expect(mutationSnapshot.permanentExtension).to.equal('permanent');
      expect(mutationSnapshot.hasTemporaryExtension).to.equal(false);
      expect(mutationSnapshot.hasPermanentExtension).to.equal(true);
      expect(mutationSnapshot.keys).to.have.members(
        Reflect.ownKeys(sharedContext)
      );
      expect(mutationSnapshot.countDescriptor).to.deep.equal(
        Object.getOwnPropertyDescriptor(sharedContext, 'count')
      );
      expect(mutationSnapshot.permanentDescriptor).to.deep.equal(
        Object.getOwnPropertyDescriptor(
          sharedContext,
          'permanentExtension'
        )
      );
      expect(sharedContext.count).to.equal(definedCount);
      expect(sharedContext).to.not.have.property('temporaryExtension');
      expect(sharedContext.permanentExtension).to.equal('permanent');
      expect(await sharedContext.count()).to.equal(73);
    });

    it('preserves live getter and setter semantics on hook-defined accessors', async function () {
      const sharedContext = {};
      let getterCalls = 0;
      let setterCalls = 0;
      let storedValue = 'initial';
      const getterReceivers = [];
      const setterReceivers = [];
      let accessorSnapshot;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(result, _args, localContext) {
          Object.defineProperty(localContext, 'dynamicExtension', {
            configurable: true,
            enumerable: true,
            get() {
              getterReceivers.push(this);
              getterCalls += 1;

              return `${storedValue}:${getterCalls}`;
            },
            set(value) {
              setterReceivers.push(this);
              setterCalls += 1;
              storedValue = value;
            }
          });
          const getterCallsAfterDefinition = getterCalls;
          const firstRead = localContext.dynamicExtension;
          const secondRead = localContext.dynamicExtension;
          const getterCallsAfterReads = getterCalls;

          localContext.dynamicExtension = 'updated';
          const getterCallsAfterSet = getterCalls;
          const readAfterSet = localContext.dynamicExtension;

          accessorSnapshot = {
            firstRead,
            getterCallsAfterDefinition,
            getterCallsAfterReads,
            getterCallsAfterSet,
            gettersUseOriginalReceiver: getterReceivers.every(
              (receiver) => receiver === localContext
            ),
            localDescriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'dynamicExtension'
            ),
            readAfterSet,
            secondRead,
            setterUsesOriginalReceiver: setterReceivers.every(
              (receiver) => receiver === localContext
            ),
            setterCalls,
            storedValue
          };

          return result;
        }
      });

      await resolveAlpha(null, {}, sharedContext, alphaInfo);

      expect(accessorSnapshot.getterCallsAfterDefinition).to.equal(0);
      expect(accessorSnapshot.firstRead).to.equal('initial:1');
      expect(accessorSnapshot.secondRead).to.equal('initial:2');
      expect(accessorSnapshot.getterCallsAfterReads).to.equal(2);
      expect(accessorSnapshot.getterCallsAfterSet).to.equal(2);
      expect(accessorSnapshot.gettersUseOriginalReceiver).to.equal(true);
      expect(accessorSnapshot.readAfterSet).to.equal('updated:3');
      expect(accessorSnapshot.setterUsesOriginalReceiver).to.equal(true);
      expect(accessorSnapshot.setterCalls).to.equal(1);
      expect(accessorSnapshot.storedValue).to.equal('updated');
      expect(accessorSnapshot.localDescriptor).to.deep.equal(
        Object.getOwnPropertyDescriptor(sharedContext, 'dynamicExtension')
      );
      expect(sharedContext.dynamicExtension).to.equal('updated:4');
    });

    it('invokes a throwing hook-defined getter only on explicit reads', async function () {
      const sharedContext = {};
      let getterCalls = 0;
      let accessorSnapshot;
      const resolveAlpha = resolver(CountAlpha, {
        list: true,
        after(result, _args, localContext) {
          Object.defineProperty(localContext, 'throwingExtension', {
            configurable: true,
            enumerable: true,
            get() {
              getterCalls += 1;
              throw new Error('accessor read failed');
            }
          });
          const getterCallsAfterDefinition = getterCalls;
          const localDescriptor = Object.getOwnPropertyDescriptor(
            localContext,
            'throwingExtension'
          );
          let readError;

          try {
            Reflect.get(localContext, 'throwingExtension');
          } catch (error) {
            readError = error;
          }

          accessorSnapshot = {
            getterCallsAfterDefinition,
            getterCallsAfterRead: getterCalls,
            localDescriptor,
            readError
          };

          return result;
        }
      });

      await resolveAlpha(null, {}, sharedContext, alphaInfo);

      expect(accessorSnapshot.getterCallsAfterDefinition).to.equal(0);
      expect(accessorSnapshot.getterCallsAfterRead).to.equal(1);
      expect(accessorSnapshot.readError).to.be.instanceOf(Error);
      expect(accessorSnapshot.readError.message).to.equal(
        'accessor read failed'
      );
      expect(accessorSnapshot.localDescriptor).to.deep.equal(
        Object.getOwnPropertyDescriptor(sharedContext, 'throwingExtension')
      );
      expect(
        Object.prototype.hasOwnProperty.call(
          sharedContext,
          'throwingExtension'
        )
      ).to.equal(true);
    });

    it('keeps deletion tombstones consistent across sibling recreation', async function () {
      const sharedContext = {
        invariantField: 'initial-invariant',
        recreatedField: 'initial-recreated'
      };
      let releaseDeleted;
      let releaseRecreated;
      const deleted = new globalThis.Promise((resolve) => {
        releaseDeleted = resolve;
      });
      const recreated = new globalThis.Promise((resolve) => {
        releaseRecreated = resolve;
      });
      let invariantSnapshot;
      let recreatedSnapshot;
      let rewrittenSnapshot;
      let sharedMissingAfterDeletion;
      const resolveDeletingSibling = resolver(CountAlpha, {
        list: true,
        async after(result, _args, localContext) {
          expect(delete localContext.recreatedField).to.equal(true);
          expect(delete localContext.invariantField).to.equal(true);
          sharedMissingAfterDeletion =
            !Object.prototype.hasOwnProperty.call(
              sharedContext,
              'recreatedField'
            ) &&
            !Object.prototype.hasOwnProperty.call(
              sharedContext,
              'invariantField'
            );
          releaseDeleted();
          await recreated;

          recreatedSnapshot = {
            descriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'recreatedField'
            ),
            has: 'recreatedField' in localContext,
            key: Reflect.ownKeys(localContext).includes('recreatedField'),
            value: localContext.recreatedField
          };
          invariantSnapshot = {
            descriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'invariantField'
            ),
            has: 'invariantField' in localContext,
            key: Reflect.ownKeys(localContext).includes('invariantField'),
            value: localContext.invariantField
          };

          localContext.recreatedField = 'local-recreated';
          rewrittenSnapshot = {
            descriptor: Object.getOwnPropertyDescriptor(
              localContext,
              'recreatedField'
            ),
            has: 'recreatedField' in localContext,
            key: Reflect.ownKeys(localContext).includes('recreatedField'),
            value: localContext.recreatedField
          };

          return result;
        }
      });
      const resolveRecreatingSibling = resolver(CountBeta, {
        list: true,
        async after(result, _args, localContext) {
          await deleted;
          localContext.recreatedField = 'sibling-recreated';
          Object.defineProperty(localContext, 'invariantField', {
            configurable: false,
            enumerable: true,
            value: 'sibling-invariant',
            writable: false
          });
          releaseRecreated();

          return result;
        }
      });

      await Promise.all([
        resolveDeletingSibling(null, {}, sharedContext, alphaInfo),
        resolveRecreatingSibling(null, {}, sharedContext, betaInfo)
      ]);

      expect(sharedMissingAfterDeletion).to.equal(true);
      expect(recreatedSnapshot).to.deep.equal({
        descriptor: {
          configurable: true,
          enumerable: true,
          value: 'sibling-recreated',
          writable: true
        },
        has: true,
        key: true,
        value: 'sibling-recreated'
      });
      expect(invariantSnapshot).to.deep.equal({
        descriptor: Object.getOwnPropertyDescriptor(
          sharedContext,
          'invariantField'
        ),
        has: true,
        key: true,
        value: 'sibling-invariant'
      });
      expect(rewrittenSnapshot).to.deep.equal({
        descriptor: Object.getOwnPropertyDescriptor(
          sharedContext,
          'recreatedField'
        ),
        has: true,
        key: true,
        value: 'local-recreated'
      });
      expect(sharedContext.recreatedField).to.equal('local-recreated');
    });
  });

  describe('prototype-named filterable attributes', function () {
    let PrototypeNamedModel;
    let prototypeNamedInfo;

    beforeAll(async function () {
      const attributes = Object.create(null);
      Object.assign(attributes, Object.fromEntries([
        ['__proto__', { type: Sequelize.STRING, field: 'proto_value' }],
        ['constructor', { type: Sequelize.STRING, field: 'constructor_value' }],
        ['toString', { type: Sequelize.STRING, field: 'to_string_value' }]
      ]));
      PrototypeNamedModel = sequelize.define(
        'resolverPrototypeNamed',
        attributes,
        { timestamps: false }
      );
      await PrototypeNamedModel.sync({ force: true });

      prototypeNamedInfo = {
        returnType: new GraphQLList(new GraphQLObjectType({
          name: 'ResolverPrototypeNamed',
          fields: {
            id: { type: GraphQLInt }
          }
        })),
        variableValues: {}
      };
    });

    it('maps inherited object names to their physical fields', async function () {
      const findAll = vi
        .spyOn(PrototypeNamedModel, 'findAll')
        .mockResolvedValue([]);
      const resolvePrototypeNamed = resolver(PrototypeNamedModel, {
        list: true,
        models: {
          [PrototypeNamedModel.name]: PrototypeNamedModel
        }
      });

      try {
        const result = await resolvePrototypeNamed(
          null,
          {
            orderBy: [
              ['__proto__', 'ASC'],
              ['constructor', 'ASC'],
              ['toString', 'ASC']
            ]
          },
          {},
          prototypeNamedInfo
        );

        expect(result).to.deep.equal([]);
        expect(findAll.mock.calls[0][0].order).to.deep.equal([
          ['proto_value', 'ASC'],
          ['constructor_value', 'ASC'],
          ['to_string_value', 'ASC']
        ]);
      } finally {
        findAll.mockRestore();
      }
    });
  });

  describe('resolved resolver targets', function () {
    const invalidResolvedTargetMessage =
      'Resolver target must resolve to a model or an association.';
    const invalidFactoryTargetMessage =
      'resolverFactory should be called with a model, an association or a function (which resolves to a model or an association)';
    const primaryKeyRequiredMessage =
      'List and Relay resolvers require a model primary key.';
    let KeylessModel;
    let keylessConnection;
    let keylessInfo;
    let keylessListInfo;

    beforeAll(async function () {
      KeylessModel = sequelize.define('resolverKeylessTarget', {
        code: Sequelize.STRING,
        status: Sequelize.STRING
      }, {
        timestamps: false
      });
      KeylessModel.removeAttribute('id');
      markFilterable(KeylessModel, 'code');
      await KeylessModel.sync({ force: true });
      await KeylessModel.create({
        code: 'only-keyless-row',
        status: 'initial'
      });

      const keylessType = new GraphQLObjectType({
        name: 'ResolverKeylessTarget',
        fields: {
          code: { type: GraphQLString },
          status: { type: GraphQLString }
        }
      });
      keylessInfo = {
        returnType: keylessType,
        variableValues: {}
      };
      keylessListInfo = {
        returnType: new GraphQLList(keylessType),
        variableValues: {}
      };
      keylessConnection = createConnection({
        name: 'ResolverKeylessTarget',
        nodeType: keylessType,
        target: KeylessModel
      });
    });

    /**
     * Build a method-complete model lookalike for target-guard tests.
     *
     * @param {object} overrides runtime fields to replace
     * @return {object} structural model lookalike
     */
    function createFauxModel(overrides = {}) {
      const rawAttributes = {
        id: {
          field: 'id',
          fieldName: 'id',
          filterable: true,
          type: { key: 'INTEGER' }
        }
      };

      return {
        count: vi.fn().mockResolvedValue(0),
        findAll: vi.fn().mockResolvedValue([]),
        findOne: vi.fn().mockResolvedValue(null),
        getAttributes: vi.fn().mockReturnValue(rawAttributes),
        getTableName: vi.fn().mockReturnValue('faux_models'),
        name: 'FauxModel',
        options: { defaultScope: {} },
        primaryKeyAttribute: 'id',
        prototype: {},
        rawAttributes,
        sequelize: { col: vi.fn() },
        update: vi.fn().mockResolvedValue([0]),
        ...overrides
      };
    }

    /**
     * Build all malformed model surfaces that previously passed the guard.
     *
     * @return {object[]} invalid model lookalikes
     */
    function createInvalidFauxModels() {
      return [
        createFauxModel({ name: undefined }),
        createFauxModel({ name: '' }),
        createFauxModel({ options: undefined }),
        createFauxModel({ options: [] }),
        createFauxModel({ rawAttributes: undefined }),
        createFauxModel({ rawAttributes: [] }),
        createFauxModel({ sequelize: undefined }),
        createFauxModel({ sequelize: { col: 'not-callable' } })
      ];
    }

    /**
     * Build association lookalikes without a callable source getter.
     *
     * @return {object[]} invalid association lookalikes
     */
    function createInvalidFauxAssociations() {
      const target = createFauxModel({ name: 'FauxTarget' });
      const validSource = createFauxModel({ name: 'FauxSource' });
      validSource.prototype.getChildren = vi.fn().mockResolvedValue([]);
      const missingGetterSource = createFauxModel({ name: 'MissingGetter' });
      const invalidGetterSource = createFauxModel({ name: 'InvalidGetter' });
      invalidGetterSource.prototype.getChildren = 'not-callable';
      const associationShape = {
        accessors: { get: 'getChildren' },
        as: 'children',
        associationType: 'HasMany',
        target
      };

      return [
        { ...associationShape },
        { ...associationShape, source: missingGetterSource },
        { ...associationShape, source: invalidGetterSource },
        { ...associationShape, source: validSource, accessors: { get: '' } }
      ];
    }

    it('reads a real keyless model directly and through a thunk', async function () {
      const directResult = await resolver(KeylessModel)(
        null,
        {},
        {},
        keylessInfo
      );
      const thunkResult = await resolver(() => KeylessModel)(
        null,
        {},
        {},
        keylessInfo
      );

      expect(directResult.code).to.equal('only-keyless-row');
      expect(thunkResult.code).to.equal('only-keyless-row');
    });

    it('updates a keyless model through an explicit where filter', async function () {
      const result = await resolver(KeylessModel, { operation: 'update' })(
        null,
        {
          data: { status: 'updated' },
          where: { code: 'only-keyless-row' }
        },
        {},
        keylessInfo
      );

      expect(result.code).to.equal('only-keyless-row');
      expect(result.status).to.equal('updated');
    });

    it('reads an explicitly ordered keyless model list', async function () {
      const result = await resolver(KeylessModel, {
        list: true,
        before(options) {
          options.order = [['code', 'ASC']];

          return options;
        }
      })(null, {}, {}, keylessListInfo);

      expect(result).to.have.length(1);
      expect(result[0].code).to.equal('only-keyless-row');
    });

    it('rejects a keyless default-order list with a controlled error', async function () {
      await expect(
        resolver(KeylessModel, { list: true })(
          null,
          {},
          {},
          keylessListInfo
        )
      ).rejects.toThrow(primaryKeyRequiredMessage);
    });

    it('rejects a keyless Relay connection with a controlled error', async function () {
      const keylessSchema = new GraphQLSchema({
        query: new GraphQLObjectType({
          name: 'ResolverKeylessQuery',
          fields: {
            keylessTargets: {
              args: keylessConnection.connectionArgs,
              resolve: keylessConnection.resolve,
              type: keylessConnection.connectionType
            }
          }
        })
      });

      const result = await graphql({
        schema: keylessSchema,
        source: `
          query {
            keylessTargets(first: 1) {
              edges {
                node {
                  code
                }
              }
            }
          }
        `
      });

      expect(result.errors).to.have.length(1);
      expect(result.errors[0].message).to.equal(primaryKeyRequiredMessage);
    });

    it('uses a thunk model name for nested model filters', async function () {
      const findAll = vi.spyOn(User, 'findAll').mockResolvedValue([]);
      const resolveUsers = resolver(() => User, {
        list: true,
        models: {
          [User.name]: User
        }
      });
      const info = {
        returnType: new GraphQLList(userType),
        variableValues: {}
      };

      try {
        const result = await resolveUsers(
          null,
          {
            where: {
              [User.name]: { name: 'resolved-name' }
            }
          },
          {},
          info
        );

        expect(result).to.deep.equal([]);
        expect(findAll.mock.calls[0][0].where).to.deep.equal({
          [`$${User.name}.name$`]: 'resolved-name'
        });
      } finally {
        findAll.mockRestore();
      }
    });

    it('supports operator filters through a model thunk', async function () {
      const expectedUser = await User.findByPk(1);
      const resolveUsers = resolver(() => User, { list: true });
      const info = {
        returnType: new GraphQLList(userType),
        variableValues: {}
      };
      const result = await resolveUsers(
        null,
        { where: { name: { eq: expectedUser.name } } },
        {},
        info
      );

      expect(result).to.have.length(1);
      expect(result[0].id).to.equal(expectedUser.id);
    });

    it('rejects invalid values returned by target thunks', async function () {
      const info = {
        returnType: new GraphQLList(userType),
        variableValues: {}
      };
      const invalidTargets = [
        null,
        { name: 'not-a-model' },
        { getTableName: 'not-callable' },
        { associationType: 'HasMany' },
        ...createInvalidFauxModels(),
        ...createInvalidFauxAssociations()
      ];

      for (const invalidTarget of invalidTargets) {
        await expect(
          resolver(() => invalidTarget)(null, {}, {}, info)
        ).rejects.toThrow(invalidResolvedTargetMessage);
      }
    });

    it('rejects invalid direct targets at factory creation', function () {
      const invalidTargets = [
        { name: 'not-a-model' },
        { getTableName: 'not-callable' },
        { associationType: 'HasMany' },
        ...createInvalidFauxModels(),
        ...createInvalidFauxAssociations()
      ];

      invalidTargets.forEach((invalidTarget) => {
        expect(() => resolver(invalidTarget)).to.throw(
          invalidFactoryTargetMessage
        );
      });
    });
  });
});
